apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: kubernetes-cluster-ashwanipratap
  labels:
    app: app-secret
data:
  DB_PASSWORD: dGVzdEAxMjM0
  FB_PASSWORD: aGFoYWhh
type: Opaque