apiVersion: v1
kind: Service
metadata:
 name: app-clusterip-service
 namespace: kubernetes-cluster-ashwanipratap
spec:
 type: ClusterIP
 ports:
 - targetPort: 8080
   port: 80
 selector:
  pod: app-pod